"""initial schema

Revision ID: 251800e2c73a
Revises:
Create Date: 2026-08-02 13:35:58.633415
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "251800e2c73a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("condition", sa.JSON(), nullable=False),
        sa.Column("action", sa.JSON(), nullable=False),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("automations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_automations_enabled"), ["enabled"], unique=False)

    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("sender", sa.String(length=320), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=1000), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("snippet", sa.String(length=300), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("category_source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("true_category", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_emails_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_emails_is_archived"), ["is_archived"], unique=False)
        batch_op.create_index(batch_op.f("ix_emails_is_read"), ["is_read"], unique=False)
        batch_op.create_index(batch_op.f("ix_emails_message_id"), ["message_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_emails_received_at"), ["received_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_emails_sender"), ["sender"], unique=False)

    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("macro_f1", sa.Float(), nullable=False),
        sa.Column("num_corrections", sa.Integer(), nullable=False),
        sa.Column("num_examples", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metrics_label"), ["label"], unique=False)

    op.create_table(
        "corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("from_category", sa.String(length=40), nullable=False),
        sa.Column("to_category", sa.String(length=40), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["email_id"], ["emails.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("corrections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_corrections_email_id"), ["email_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_corrections_to_category"), ["to_category"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("corrections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corrections_to_category"))
        batch_op.drop_index(batch_op.f("ix_corrections_email_id"))

    op.drop_table("corrections")
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metrics_label"))

    op.drop_table("metrics")
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_emails_sender"))
        batch_op.drop_index(batch_op.f("ix_emails_received_at"))
        batch_op.drop_index(batch_op.f("ix_emails_message_id"))
        batch_op.drop_index(batch_op.f("ix_emails_is_read"))
        batch_op.drop_index(batch_op.f("ix_emails_is_archived"))
        batch_op.drop_index(batch_op.f("ix_emails_category"))

    op.drop_table("emails")
    with op.batch_alter_table("automations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automations_enabled"))

    op.drop_table("automations")
    # ### end Alembic commands ###
