"""add email.secondary

Revision ID: f880ad7de108
Revises: 251800e2c73a
Create Date: 2026-08-02 15:49:33.427212
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f880ad7de108"
down_revision: str | None = "251800e2c73a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.add_column(sa.Column("secondary", sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_column("secondary")

    # ### end Alembic commands ###
